theme = "onedark-trans"

[editor]
line-number = "relative"
mouse = true 
true-color = true
auto-pairs = true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "none"
