#!/bin/dash
#
# ~/.xmonad/build
#
#
# complete build with $ stack build
#

exec stack ghc \
   --stack-yaml stack.yaml \
   -- \
   --make xmonad.hs \
   -i \
   -ilib \
   -fforce-recomp \
   -main-is main \
   -v0 \
   -outputdir build-x86_64-linux \
   -o "$1" 
